// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: srpc.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "srpc.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace srpc {

namespace {

const ::google::protobuf::Descriptor* UnifiedReq_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  UnifiedReq_reflection_ = NULL;
const ::google::protobuf::ServiceDescriptor* GlobalService_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_srpc_2eproto() {
  protobuf_AddDesc_srpc_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "srpc.proto");
  GOOGLE_CHECK(file != NULL);
  UnifiedReq_descriptor_ = file->message_type(0);
  static const int UnifiedReq_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UnifiedReq, cmd_),
  };
  UnifiedReq_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      UnifiedReq_descriptor_,
      UnifiedReq::default_instance_,
      UnifiedReq_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UnifiedReq, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UnifiedReq, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(UnifiedReq));
  GlobalService_descriptor_ = file->service(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_srpc_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    UnifiedReq_descriptor_, &UnifiedReq::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_srpc_2eproto() {
  delete UnifiedReq::default_instance_;
  delete UnifiedReq_reflection_;
}

void protobuf_AddDesc_srpc_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\nsrpc.proto\022\004srpc\"\031\n\nUnifiedReq\022\013\n\003cmd\030"
    "\001 \001(\0052A\n\rGlobalService\0220\n\nGlobalCall\022\020.s"
    "rpc.UnifiedReq\032\020.srpc.UnifiedReqB\003\200\001\001", 117);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "srpc.proto", &protobuf_RegisterTypes);
  UnifiedReq::default_instance_ = new UnifiedReq();
  UnifiedReq::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_srpc_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_srpc_2eproto {
  StaticDescriptorInitializer_srpc_2eproto() {
    protobuf_AddDesc_srpc_2eproto();
  }
} static_descriptor_initializer_srpc_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int UnifiedReq::kCmdFieldNumber;
#endif  // !_MSC_VER

UnifiedReq::UnifiedReq()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void UnifiedReq::InitAsDefaultInstance() {
}

UnifiedReq::UnifiedReq(const UnifiedReq& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void UnifiedReq::SharedCtor() {
  _cached_size_ = 0;
  cmd_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

UnifiedReq::~UnifiedReq() {
  SharedDtor();
}

void UnifiedReq::SharedDtor() {
  if (this != default_instance_) {
  }
}

void UnifiedReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* UnifiedReq::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return UnifiedReq_descriptor_;
}

const UnifiedReq& UnifiedReq::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_srpc_2eproto();
  return *default_instance_;
}

UnifiedReq* UnifiedReq::default_instance_ = NULL;

UnifiedReq* UnifiedReq::New() const {
  return new UnifiedReq;
}

void UnifiedReq::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    cmd_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool UnifiedReq::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 cmd = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &cmd_)));
          set_has_cmd();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void UnifiedReq::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional int32 cmd = 1;
  if (has_cmd()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->cmd(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* UnifiedReq::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional int32 cmd = 1;
  if (has_cmd()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->cmd(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int UnifiedReq::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int32 cmd = 1;
    if (has_cmd()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->cmd());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void UnifiedReq::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const UnifiedReq* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const UnifiedReq*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void UnifiedReq::MergeFrom(const UnifiedReq& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_cmd()) {
      set_cmd(from.cmd());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void UnifiedReq::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void UnifiedReq::CopyFrom(const UnifiedReq& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UnifiedReq::IsInitialized() const {

  return true;
}

void UnifiedReq::Swap(UnifiedReq* other) {
  if (other != this) {
    std::swap(cmd_, other->cmd_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata UnifiedReq::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = UnifiedReq_descriptor_;
  metadata.reflection = UnifiedReq_reflection_;
  return metadata;
}


// ===================================================================

GlobalService::~GlobalService() {}

const ::google::protobuf::ServiceDescriptor* GlobalService::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return GlobalService_descriptor_;
}

const ::google::protobuf::ServiceDescriptor* GlobalService::GetDescriptor() {
  protobuf_AssignDescriptorsOnce();
  return GlobalService_descriptor_;
}

void GlobalService::GlobalCall(::google::protobuf::RpcController* controller,
                         const ::srpc::UnifiedReq*,
                         ::srpc::UnifiedReq*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method GlobalCall() not implemented.");
  done->Run();
}

void GlobalService::CallMethod(const ::google::protobuf::MethodDescriptor* method,
                             ::google::protobuf::RpcController* controller,
                             const ::google::protobuf::Message* request,
                             ::google::protobuf::Message* response,
                             ::google::protobuf::Closure* done) {
  GOOGLE_DCHECK_EQ(method->service(), GlobalService_descriptor_);
  switch(method->index()) {
    case 0:
      GlobalCall(controller,
             ::google::protobuf::down_cast<const ::srpc::UnifiedReq*>(request),
             ::google::protobuf::down_cast< ::srpc::UnifiedReq*>(response),
             done);
      break;
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      break;
  }
}

const ::google::protobuf::Message& GlobalService::GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::srpc::UnifiedReq::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *reinterpret_cast< ::google::protobuf::Message*>(NULL);
  }
}

const ::google::protobuf::Message& GlobalService::GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::srpc::UnifiedReq::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *reinterpret_cast< ::google::protobuf::Message*>(NULL);
  }
}

GlobalService_Stub::GlobalService_Stub(::google::protobuf::RpcChannel* channel)
  : channel_(channel), owns_channel_(false) {}
GlobalService_Stub::GlobalService_Stub(
    ::google::protobuf::RpcChannel* channel,
    ::google::protobuf::Service::ChannelOwnership ownership)
  : channel_(channel),
    owns_channel_(ownership == ::google::protobuf::Service::STUB_OWNS_CHANNEL) {}
GlobalService_Stub::~GlobalService_Stub() {
  if (owns_channel_) delete channel_;
}

void GlobalService_Stub::GlobalCall(::google::protobuf::RpcController* controller,
                              const ::srpc::UnifiedReq* request,
                              ::srpc::UnifiedReq* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(0),
                       controller, request, response, done);
}

// @@protoc_insertion_point(namespace_scope)

}  // namespace srpc

// @@protoc_insertion_point(global_scope)
