// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: srpc.proto

#ifndef PROTOBUF_srpc_2eproto__INCLUDED
#define PROTOBUF_srpc_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/service.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace srpc {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_srpc_2eproto();
void protobuf_AssignDesc_srpc_2eproto();
void protobuf_ShutdownFile_srpc_2eproto();

class UnifiedReq;

// ===================================================================

class UnifiedReq : public ::google::protobuf::Message {
 public:
  UnifiedReq();
  virtual ~UnifiedReq();

  UnifiedReq(const UnifiedReq& from);

  inline UnifiedReq& operator=(const UnifiedReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UnifiedReq& default_instance();

  void Swap(UnifiedReq* other);

  // implements Message ----------------------------------------------

  UnifiedReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UnifiedReq& from);
  void MergeFrom(const UnifiedReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 cmd = 1;
  inline bool has_cmd() const;
  inline void clear_cmd();
  static const int kCmdFieldNumber = 1;
  inline ::google::protobuf::int32 cmd() const;
  inline void set_cmd(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:srpc.UnifiedReq)
 private:
  inline void set_has_cmd();
  inline void clear_has_cmd();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 cmd_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_srpc_2eproto();
  friend void protobuf_AssignDesc_srpc_2eproto();
  friend void protobuf_ShutdownFile_srpc_2eproto();

  void InitAsDefaultInstance();
  static UnifiedReq* default_instance_;
};
// ===================================================================

class GlobalService_Stub;

class GlobalService : public ::google::protobuf::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline GlobalService() {};
 public:
  virtual ~GlobalService();

  typedef GlobalService_Stub Stub;

  static const ::google::protobuf::ServiceDescriptor* descriptor();

  virtual void GlobalCall(::google::protobuf::RpcController* controller,
                       const ::srpc::UnifiedReq* request,
                       ::srpc::UnifiedReq* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::google::protobuf::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::google::protobuf::MethodDescriptor* method,
                  ::google::protobuf::RpcController* controller,
                  const ::google::protobuf::Message* request,
                  ::google::protobuf::Message* response,
                  ::google::protobuf::Closure* done);
  const ::google::protobuf::Message& GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const;
  const ::google::protobuf::Message& GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(GlobalService);
};

class GlobalService_Stub : public GlobalService {
 public:
  GlobalService_Stub(::google::protobuf::RpcChannel* channel);
  GlobalService_Stub(::google::protobuf::RpcChannel* channel,
                   ::google::protobuf::Service::ChannelOwnership ownership);
  ~GlobalService_Stub();

  inline ::google::protobuf::RpcChannel* channel() { return channel_; }

  // implements GlobalService ------------------------------------------

  void GlobalCall(::google::protobuf::RpcController* controller,
                       const ::srpc::UnifiedReq* request,
                       ::srpc::UnifiedReq* response,
                       ::google::protobuf::Closure* done);
 private:
  ::google::protobuf::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(GlobalService_Stub);
};


// ===================================================================


// ===================================================================

// UnifiedReq

// optional int32 cmd = 1;
inline bool UnifiedReq::has_cmd() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UnifiedReq::set_has_cmd() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UnifiedReq::clear_has_cmd() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UnifiedReq::clear_cmd() {
  cmd_ = 0;
  clear_has_cmd();
}
inline ::google::protobuf::int32 UnifiedReq::cmd() const {
  return cmd_;
}
inline void UnifiedReq::set_cmd(::google::protobuf::int32 value) {
  set_has_cmd();
  cmd_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace srpc

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_srpc_2eproto__INCLUDED
